---
- name: Install IIS
  hosts: all
  gather_facts: true
  tasks:
    - name: Install IIS Web-Server with sub features and management tools
      win_feature:
        name: Web-Server
        state: present
        include_sub_features: no
        include_management_tools: yes
      register: win_feature
